// Generated by LiveScript 1.2.0
(function(){
  var util, utily, subject, Debugger, RuleApplier, ApplyContext, inspect, RulesApplier;
  util = require('../util');
  utily = require('../../util');
  subject = utily.subject;
  Debugger = utily.Debugger;
  RuleApplier = require('../rule').RuleApplier;
  ApplyContext = require('../apply_context');
  inspect = require('util').inspect;
  module.exports = RulesApplier = (function(){
    RulesApplier.displayName = 'RulesApplier';
    var prototype = RulesApplier.prototype, constructor = RulesApplier;
    importAll$(prototype, arguments[0]);
    function RulesApplier(applyContext, rules, debugging){
      this.applyContext = applyContext;
      this.rules = rules;
      this.debugging = debugging;
      this._validate();
      this;
    }
    prototype._validate = function(){
      if (!(this.applyContext.ucan && this.applyContext.ucannot)) {
        throw Error("Apply context must have ucan and ucannot methods for applying rules, was: " + inspect(this.applyContext));
      }
    };
    prototype.repo = function(){
      return this.applyContext.repo;
    };
    prototype.apply = function(thing, ctx){
      return this.ruleApplier(thing, ctx).apply();
    };
    prototype.ruleApplier = function(thing, ctx){
      return new RuleApplier(thing, ctx);
    };
    prototype.applyAll = function(){
      var rules, key, results$ = [];
      switch (typeof this.rules) {
      case 'object':
        rules = this.rules;
        for (key in rules) {
          results$.push(util.recurse(rules[key], this.applyContext));
        }
        return results$;
        break;
      default:
        throw Error("rules must be an Object was: " + typeof this.rules);
      }
    };
    return RulesApplier;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
