// Generated by LiveScript 1.2.0
(function(){
  var Debugger, util, ApplyContext, toString$ = {}.toString;
  Debugger = require('../../util').Debugger;
  util = require('util');
  module.exports = ApplyContext = (function(){
    ApplyContext.displayName = 'ApplyContext';
    var prototype = ApplyContext.prototype, constructor = ApplyContext;
    importAll$(prototype, arguments[0]);
    function ApplyContext(repo, debugging){
      this.repo = repo;
      this.debugging = debugging;
      this.debug('execute context', this.repo);
      this._validate();
      this;
    }
    prototype._type = 'ApplyContext';
    prototype._validate = function(){
      if (toString$.call(this.repo).slice(8, -1) !== 'Object') {
        throw Error("ExecutionContext must take an Object, was: " + util.inspect(this.repo));
      }
    };
    prototype.ucan = function(actions, subjects, ctx){
      this.debug('register ucan', actions, subjects, ctx);
      this.repo.register('can', actions, subjects, ctx);
      return this.debug('Registered :)');
    };
    prototype.ucannot = function(actions, subjects, ctx){
      this.debug('ucannot', actions, subjects, ctx);
      this.repo.register('cannot', actions, subjects, ctx);
      return this.debug('Registered :)');
    };
    return ApplyContext;
  }(Debugger));
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
