// Generated by LiveScript 1.2.0
(function(){
  var rule, RuleApplier, ExecutionContext, fixtures, User, Book, expect, createApplier;
  require('../../test_setup');
  rule = require('../../../index');
  RuleApplier = rule.apply.single.RuleApplier;
  ExecutionContext = rule.apply.ExecutionContext;
  fixtures = require('../../fixtures');
  User = fixtures.user;
  Book = fixtures.book;
  expect = require('chai').expect;
  createApplier = function(rules, name, context, debug){
    debug == null && (debug = true);
    return new RuleApplier(rules, name, context, debug);
  };
  describe('RuleApplier', function(){
    var applier, ctx, object;
    return context('invalid', function(){
      return specify('throws', function(){
        return expect(createApplier({}, void 8)).to['throw'];
      });
    });
  });
}).call(this);
